### ISSUE TITLE
Can't start error ImportError in webui.py 

### ISSUE THREAD

**Issue by tuangd** [TheLastBen/fast-stable-diffusion#1128]
Can't launch.
This always show up.
```Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules import import_hook
ImportError: cannot import name 'import_hook' from 'modules' (unknown location)
```
Not sure what to do now.

**Comment by EleVicted** [comment]
^ same issue

**Comment by ibushong** [comment]
This appears to be due to a recent update to the AUTOMATIC1111 repo. The notebook is doing a shallow clone of the repo, along with some manual wget (which is kind of odd/confusing. Why not just clone the whole repo?)

It wont work until the notebook is updated to grab these new files (or just the whole repo, which IMO would be much simpler)

**Comment by TheLastBen** [comment]
@ibushong what is confusing you ?

**Comment by ibushong** [comment]
> @ibushong what is confusing you ?

Mainly: why don't you just clone the whole repo?

**Comment by TheLastBen** [comment]
> Mainly: why don't you just clone the whole repo?
I'm cloning the whole repo, but some files have to be modified to make sure everything is compatible with colab, so each file modified had to be removed before pulling updates, then redownloaded fresh later.

**Comment by ibushong** [comment]
> I'm cloning the whole repo, but some files have to be modified to make sure everything is compatible with colab, so each file modified had to be removed before pulling updates, then redownloaded fresh later.

Ugh, my apologies, I don't have much/any experience with the `--depth 1` param, so I assumed it was only cloning the first level of the directory structure (which is a silly assumption in retrospect). Sorry about that.

Though I'm still curious about the colab compatibility issues, since there are some "thinner" notebooks that still seem to work fine, like [this](https://github.com/ddPn08/automatic1111-colab/blob/main/automatic1111.ipynb) one -- as far as I can tell, most of the code is for 1) separating code from data/config and 2) enabling some optimizations (like python 3.10, xformers, etc). Perhaps some of the issues you're accounting for have been resolved in the current A1111 repo?

**Comment by TheLastBen** [comment]
!rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.sh # sometimes it blocks the pull
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py # to set up the "sd" folder
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py "to activate the gradio queue"
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py "to fix some issues with the css style"
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/style.css "make the orange button a bit bigger to allow generating in a case of a ui freeze
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py    #to allow large model loading and fix RAM error

**Comment by ibushong** [comment]
Nice. Thanks for the details/clarification (the orange button hack is super useful). I'm pretty new to SD so I'm def missing some context. Anyway, I appreciate your work and responses!
