### ISSUE TITLE
How to use new "Manual captioning" feature?

### ISSUE THREAD

**Issue by iqddd** [TheLastBen/fast-stable-diffusion#1180]
How to use the new "Manual Captioning" function?
Why is it needed at all, what advantages does it provide?

**Comment by TheLastBen** [comment]
Captions are useful when enhancing existing instances, say you want to enhance a specific brand of a car, in the caption, you add the car's specific brand, avoid using class terms "car" otherwise you will force the model to converge too fast, stick to proper names like "Toyota" or "Honda CBR1000RR-R FIREBLADE" ...

**Comment by brandonkoch3** [comment]
Could you elaborate on how we might use the Manual Captioning function?  For example, if I have ten photos of my face, and they are labeled "bob (1).jpg", "bob (2).jpg", "bob (3).jpg", etc., and I opt to use the new manual captioning feature, what should I type in for each photo?  Should they be more detailed descriptions of each photo (such as "Bob wearing a white sweater standing in front of a tall tree") or should they be more tokenized (such as "Bob, white sweater, standing, tall tree")?

**Comment by TheLastBen** [comment]
if you are training a face, you don't need captioning, captioning is for style with complicated compositions or movies.
also don't use "bob" as an instance name, use something like "ytutszviont" a non-existing word to avoid getting merged with an existing bob.
