### ISSUE TITLE
Retraining help needed

### ISSUE THREAD

**Issue by Brandyfan** [TheLastBen/fast-stable-diffusion#1456]
I recently trained a model on a cartoon character and it turned out pretty good with some images even better than I had expected! Now I noticed there's a facial expression I forgot to include when I did the training, in this case, the facial expression of the character with her tongue sticking out. I have one picture showing what her tongue looks like, but I can get more if that's not enough to add to the previously trained model. 
So my questions are,
1. Can you train a facial expression using just one picture for something as minor as a tongue sticking out to a model that's already trained or should I get more?
2. With the training, I've been doing 100 unet steps per picture and that gave me the best results, For adding on an additional picture, how many steps would you suggest and should I change any other settings?
3. Finally, would I put this under "instance images" or "concept images?"

Thanks so much for any help! :)

**Comment by TheLastBen** [comment]
It's a bit tricky adding just one image to the training, first of all, you need to backup your model or simply use that model as the base model putting its path in the download model cell, so that every time you start the training over, it will load the original model that you trained.
try putting only that picture as an instance image, then set the unet steps to 0, and set the **text encoder steps to 30 at 2e-6.**

**Comment by Brandyfan** [comment]
Thanks for the help! It appears to be working pretty good now.

**Comment by Brandyfan** [comment]
Just a quick question, how many steps would you suggest per picture? Like say I had 2 pictures to add to the model that's already trained. Is it generally 30 steps at 2e-6 for the text encoder for each picture meaning I would do 60 for two pictures? Just trying to get a general idea of how much training would be needed per picture if I add more in the future.
