### ISSUE TITLE
train_only_unet trains also text_encoder

### ISSUE THREAD

**Issue by manofearth** [TheLastBen/fast-stable-diffusion#1572]
The issue is related to https://github.com/TheLastBen/diffusers repository more, but I can't post an issue there, so I'm posting here.

Isn't it a bug that when saving a model here: https://github.com/TheLastBen/diffusers/blob/604952fc942137ee480178488614ac5d85cf9347/examples/dreambooth/train_dreambooth.py#L781 text encoder is also saved?

As far as I understand it means that 

- after text encoder trained together with unet for Text_Encoder_Concept_Training_Steps with Text_Encoder_Learning_Rate and saved to `text_encoder_trained` folder (unet weights are discarded)
- it trained again from this ↑ state toghether with unet for UNet_Training_Steps with UNet_Learning_Rate and saved to `text_encoder` folder (text_encoder weights are NOT discarded)

As a result we have a model with text_encoder trained twice, though expected to be trained just once. So am I missing something?

**Comment by TheLastBen** [comment]
After training the text encoder, the resulting text encoder model is saved in `text_encoder_trained` then when the unet starts training, if there is a folder named `text_encoder_trained`, it will load it instead of the base, and during the unet training, the text encoder is not trained, so at the end when it saves the model, it dumps the previously trained text encoder and the current trained unet.

**Comment by manofearth** [comment]
Oh, now I see. It is because [here](https://github.com/TheLastBen/diffusers/blob/updt/examples/dreambooth/train_dreambooth.py#L536) text_encoder params do not pass in optimiser. I'm sorry for my hasty conclusion.
