### ISSUE TITLE
ControlNet for Fast-stable-diffusion?

### ISSUE THREAD

**Issue by xITmasterx** [TheLastBen/fast-stable-diffusion#1596]
I'm just wondering if it's possible to integrate just the extension of ControlNet into the colab, it's becoming really good and useful for img2img, especially for different things like posing and composition.

**Comment by animeking527** [comment]
You can easily install the extension when you run the colab and then add the ControlNet models in your new ControlNet folder in your webui gdrive and you'll have it. Since there's so many models I don't think it'd be realistic to have the colab automatically download them all. Aitrepreneur's latest video on Youtube shows the process locally. Only difference is your sd folder is in your gdrive.

**Comment by eliasprompt** [comment]
> 

I have tried it but at the moment of starting the process of generating the image it stops working in Colab and crashes

**Comment by jkmo90** [comment]
mine does not crash, but whenever i try to use an input image in the controlnet extension, the preprocessing does not work. It just comes out as a blank image.

**Comment by animeking527** [comment]
@eliasprompt I've had to restart the last cell in colab because it crashes when switching between the ControlNet models, so you may just need to restart when it crashes. 

Makes sure you put the picture you're wanting to analyze in the extension window and the size settings correct before running or else it'll get confused too and you may need to restart.

@jkmo90 Some images it's difficult to find the pose and it'll turn out black. But that only happened on images I didn't really expect to work since there were tough poses or obscured.

So far I've only tested the openpose and depth models.

**Comment by jkmo90** [comment]
@animeking527 interesting... it seems like no matter what model i use, the preprocessing never works for actual images. If i click "open drawing canvas" and draw an image manually, that works.

**Comment by eliasprompt** [comment]
@animeking527 I've only been able to get it to work once in 10+ tries. Always stops after the msg and nothing happens

Loading preprocessor: openpose, model: control_sd15_openpose [fef5e48e]

**Comment by jkmo90** [comment]
it works for me now, had to switch browsers.

**Comment by eliasprompt** [comment]
I have tried with chrome and firefox and nothing, it always stops with the same message

**Comment by animeking527** [comment]
@eliasprompt how long are you waiting for it to load? It does take a few minutes. Make sure to be running the newest version of the notebook and give it at least 7 minutes to load the controlnet model.

**Comment by willy1322** [comment]
same here stuck at loading ControlNet processor

**Comment by aksiomweb** [comment]
The preprocessor select box has options, but the model select box next to it doesn't.
Hitting the refresh button does not solve for me. 

Notebook generates this error: 
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 270, in process
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None

**Comment by Daviljoe193** [comment]
@eliasprompt I know this won't sound like an appealing suggestion, but try doing exactly what you did before, 1:1, as an update to the repo should allow model loading to work reliably.

**Comment by cerarslan** [comment]
I always get black images for maps. Anyone face with issue before?

**Comment by TheLastBen** [comment]
ControlNet Added and it works

**Comment by cerarslan** [comment]
> ControlNet Added and it works

Thank you so much Ben! You are doing great jobs. I appreciate to you.

**Comment by xITmasterx** [comment]
Thanks man, I really do appreciate it. Closing issue.
