### ISSUE TITLE
 cannot import name 'hashes' from 'modules'

### ISSUE THREAD

**Issue by AlexChen1955** [TheLastBen/fast-stable-diffusion#1618]
How to solve this problem?
When I install LoRA, did not appear additional network switch.
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

**Comment by kevin202108** [comment]
I have the same promble with you.
I think it is because there is no file 'hashes' in our  folder 'modules'?
but I don't know how to fix it.

I have pulled SD and lora to up-to-date.

And I asked Bing, and it tell me that it may because:
[This error may occur if you have a circular import or an outdated version of cryptography module](https://github.com/pyca/cryptography/issues/4770)[1](https://github.com/pyca/cryptography/issues/4770). [You can try to update your cryptography module using 'pip install -U cryptography' or check your import statements for any loops](https://stackoverflow.com/questions/17845366/importerror-cannot-import-name)[2](https://stackoverflow.com/questions/17845366/importerror-cannot-import-name)[3](https://stackoverflow.com/questions/70617834/importerror-cannot-import-name-class-from-module).
I have tried the pip method in venv and modules folder, but it didn't work.

When I tried to download SD, I deleted my old version Python and download 3.10.6 to the same folder.
And I forgot to add it to my PATH, so I tried to edit my Environmental Variables and finally used the installer to do that.
And I think I used pip to install torch.
I don't know do these matter, but I just want to mention the whole picture.

**Comment by TheLastBen** [comment]
Try with a clean SD folder by renaming/removing the existing one.

**Comment by AlexChen1955** [comment]
I have reinstalled SD succeeded. Thank you very much.

**Comment by TheLastBen** [comment]
great!
