### ISSUE TITLE
Help with error: "AttributeError: 'Namespace' object has no attribute 'nowebui'"

### ISSUE THREAD

**Issue by highlyillliquid** [TheLastBen/fast-stable-diffusion#178]
Hi I'm getting the following error after trying to run the "Start stable-diffusion" cell. 

I've run this notebook several times in the past without issue. 

Can anyone help with the issue? Thanks!

<img width="955" alt="Screen Shot 2022-10-19 at 3 45 11 PM" src="https://user-images.githubusercontent.com/7577820/196648860-3d811e1d-b18e-455b-ae11-f3427d2ced4c.png">

**Comment by FabMariani** [comment]
Getting the same since yesterday, out of nowhere. 

The last time I had an error like that out of nowhere was a week or so ago, it went on for 3 days and resumed normally. The error back then was related to taming. 

Following this post but for the time being I'm just going to wait it out a few days, see if somehow things pan out.

**Comment by Arnold2006** [comment]
Had the same issue. Ran all steps again and made sure to update the Repo.
Now it works again :)

**Comment by highlyillliquid** [comment]
> Had the same issue. Ran all steps again and made sure to update the Repo. Now it works again :)

I tried that too, but I'm still getting the same error msg 😪

**Comment by TheLastBen** [comment]
@highlyillliquid update the repo and use the latest colab, if the error persists, remove the folder "sd" and do a clean run

**Comment by highlyillliquid** [comment]
> @highlyillliquid update the repo and use the latest colab, if the error persists, remove the folder "sd" and do a clean run

This worked! Thank you.

**Comment by TheLastBen** [comment]
Great!
