### ISSUE TITLE
about project unstability

### ISSUE THREAD

**Issue by FVolral** [TheLastBen/fast-stable-diffusion#2405]
Hello Ben, it's been months since I've been using your Google Colab, and even though I recognize your dedication and hard work, I'm starting to get really fed up with the instability of this project. Almost every day, it crashes for a different reason, and it's extremely frustrating. I even recently helped fix a bug (https://github.com/TheLastBen/fast-stable-diffusion/issues/2343#issuecomment-1642716471). I know it's not entirely your fault because I see the minor changes you make to Colab, but still, I'd like to understand why we constantly encounter these breaking changes. Is it because Google keeps updating its packages all the time? Or is it because automatic1111's project is constantly evolving and breaking everything? I just want to understand

**Comment by lschaupp** [comment]
The reason is because this repository does not follow common software practices ;)
I have forked this repository and made static versions myself where everything is static.
Mostly it gets broken through A1111 changes. This repository pulls always the latest changes from the main branch (at every run). Of course this will break things. There is no versioning within this repository either.

The runpod images do help though. But even there things are getting downloaded from some github repos.

**Comment by TheLastBen** [comment]
Google colab is updating their backend and A1111 is updating every 15 days, even then, any instability lasts only a few hours, most of the issues are caused by the users themselves not using high-RAM runtimes.

**Comment by FVolral** [comment]
Thank you for your responses, at least that way it's clearer

**Comment by FVolral** [comment]
thank you for your answer
