### ISSUE TITLE
ModuleNotFoundError: No module named 'pillow_avif'

### ISSUE THREAD

**Issue by roman19932024** [TheLastBen/fast-stable-diffusion#2812]
Everything was working fine yesterday on Google Collab
but today at the "Start Stable-Diffusion" stage I have a sudden error message ending by ModuleNotFoundError: No module named 'pillow_avif', anyone can help me on this?
![error](https://github.com/TheLastBen/fast-stable-diffusion/assets/167762241/1f95c9e5-5539-4657-bf5b-04d4713138bf)

**Comment by thomaslee101** [comment]
i had the same "no module named 'pillow_avif' error, so i deleted the whole SD folder and reinstalled a new copy of the automatic1111. now i have a different error, which is this. hope someone can look into this as well.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-09b31cc1a357>](https://localhost:8080/#) in <cell line: 6>()
      4 import sys
      5 import fileinput
----> 6 from pyngrok import ngrok, conf
      7 import re
      8 

ModuleNotFoundError: No module named 'pyngrok'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by sixpt** [comment]
Ditto, I get the same pillow_avif error in my typical notebook as well as a new one with fresh install

**Comment by atomfurs** [comment]
If you're missing pillow-avif add a line of code and run -  !pip install pillow-avif-plugin

**Comment by leshuys** [comment]
> i had the same "no module named 'pillow_avif' error, so i deleted the whole SD folder and reinstalled a new copy of the automatic1111. now i have a different error, which is this. hope someone can look into this as well.
> 
> ModuleNotFoundError Traceback (most recent call last) in <cell line: 6>() 4 import sys 5 import fileinput ----> 6 from pyngrok import ngrok, conf 7 import re 8
> 
> ModuleNotFoundError: No module named 'pyngrok'
> 
> NOTE: If your import is failing due to a missing package, you can manually install dependencies using either !pip or !apt.
> 
> ## To view examples of installing some common dependencies, click the
> "Open Examples" button below.

Im getting this error today

**Comment by AlfaShot111** [comment]
same error today appeared

**Comment by lemon-lemom** [comment]
You can solve this problem by installing the library.
For your reference
https://colab.research.google.com/drive/14vEexu7JNPFfI4pSoeghXZA4GCgh2B-v?usp=sharing

**Comment by lemon-lemom** [comment]
You can solve this problem by installing the library.
For your reference
https://colab.research.google.com/drive/14vEexu7JNPFfI4pSoeghXZA4GCgh2B-v?usp=sharing

**Comment by dymension** [comment]
> If you're missing pillow-avif add a line of code and run - !pip install pillow-avif-plugin

Thanks for the solution

**Comment by aifantasyglam** [comment]
> If you're missing pillow-avif add a line of code and run - !pip install pillow-avif-plugin

thanks a lot, works perfect

**Comment by TheLastBen** [comment]
fixed

**Comment by ChrisWang13** [comment]
> Yes that fixed it for me too, I had added both of those lines before Requirements step
> 
> !pip install diskcache !pip install pillow-avif-plugin

It worked for me from updating to this newer version. Thanks!
