### ISSUE TITLE
a simple gradio UI version with just a text box for the prompt

### ISSUE THREAD

**Issue by GeorvityLabs** [TheLastBen/fast-stable-diffusion#8]
both the notebooks used here , seems to be super complex.
to keep things simple , i was wondering that :
it would be great if there is a way to link 25% faster technique to a simple gradio ui , implemented within the notebook file itself.
with just a text box and submit button.
would be dope if someone could implement it with gradio blocks, such that the model is accessed from a local model path

**Comment by TheLastBen** [comment]
I will soon add a relaxed mode notebook, which will concentrate on the output image rather than the settings, like this one (I tuned for my personal use) :
[https://i.postimg.cc/6q9v3HZY/Capturerea.jpg](url)

**Comment by GeorvityLabs** [comment]
that looks interesting @TheLastBen , looking forward to it.

**Comment by GeorvityLabs** [comment]
any way to strip your current relaxed mode , to make a super basic version , with just a prompt box and submit button , like the official hugginface demo for stable diffusion .
or like DALL-E 2 demo , keeping it super clean and interesting to build upon.

**Comment by TheLastBen** [comment]
But the resolution and the number of steps and the cfg scale are very important in stable diffusion

**Comment by GeorvityLabs** [comment]
true @TheLastBen , those can be available.

**Comment by GuruVirus** [comment]
Regarding the main topic of a simpler version of the GUI.
On mobile devices the slider bars are imprecise and very laggy. I prefer the text box inputs as seen in the Image Creation section of this colab: https://colab.research.google.com/github/pharmapsychotic/ai-notebooks/blob/main/pharmapsychotic_Stable_Diffusion.ipynb

Honestly a simple set of text boxes on PC is way faster too so you can tab thru them. Maybe a checkbox at the top for "input fields instead of sliders" or have both sliders and a text field next to them?

I basically only run 704x704 or 512x896. Though the webUI has been so efficient I have been able to try larger resolutions. 1024x1024 I think went thru and saved, but then it crashed the Generate button (appears to be the same Gradio connector issue as the batch failure problem).

**Comment by AK391** [comment]
@GuruVirus for mobile you might want to try this gradio gui on huggingface, mininal version with less features: https://huggingface.co/spaces/stabilityai/stable-diffusion
