### ISSUE TITLE
Generate button stopped working after generating one image

### ISSUE THREAD

**Issue by gateeeeee** [TheLastBen/fast-stable-diffusion#966]
For the auto1111 notebook, after generating one image, the generate button stopped working. 

The problem persists after the "attempt to fix Gradio freeze" fix.

Edit:
I did a refresh and now it worked. Let me experiment further.

**Comment by zzaisd** [comment]
Same issue, have to refresh everytime after generating one set of images

**Comment by gateeeeee** [comment]
Seems to be working fine except when using the X/Y plot. No image preview and the generation button stopped working after the first batch.

**Comment by rokey-z** [comment]
Same problem, no image preview if you do multiple generations, then it stuck, you have to restart the UI. 
But if you only generate 1  image, preview shows, and you can do next round.

**Comment by TheLastBen** [comment]
I'm looking for a solution

**Comment by createperhaps** [comment]
Use the gradio server, worked for me

**Comment by jn-jairo** [comment]
I have the same problem, but only if the image generated is too big, like a x/y grid, the thumbnail doesn't show and the generate button doesn't work, not even the shortcut Ctrl + Enter, I have to refresh to make it work again.

Looks like it can't handle the big image, or it's some racing condition, the big image takes too long to process and it stucks, maybe the output folder been inside gdrive is making it happens here but not in other environments, because it is slower with the mounting point.

**Comment by BrokedTV** [comment]
> Use the gradio server, worked for me

Gradio indeed works fine!

**Comment by juan9999** [comment]
Gradio is better but when you leave the browser window say to go to another tab like colab while you're rendering and you come back, either the generate button or the previews don't load.

I'm running a model I trained based on SD 2.1 768 typically with these settings
Steps: 80, Sampler: Euler a, CFG scale: 10, Size: 768x768, Model hash: 1b51225c, Batch size: 4

Would love a solution to this as pressing reload is a pain as I have to reenter all the parameters

I've tried playing arounds with the 1111 settings (such as preview etc) but can't seem to find the root cause.

**Comment by gateeeeee** [comment]
> 

I find that to be the case. When I generate a 1024x1024 it works fine. But whenever a 1408x1024, the preview pic doesn't load and the generate button stops working. Same with generating a X/Y grid with high res.

Gradio server also has problems like the ones juan9999 mentioned above.

**Comment by TheLastBen** [comment]
I set the default to gradio server, and changed few settings with gradio queue, you shouldn't face this issue anymore, use the updated colab

**Comment by gateeeeee** [comment]
> I set the default to gradio server, and changed few settings with gradio queue, you shouldn't face this issue anymore, use the updated colab

Just tested a bit, the problems are gone. Thanks :)

**Comment by Ktr4ks** [comment]
Am I the only one that has problems using the Gradio server? The ui always freezes when I use it. It was always like this.

**Comment by gateeeeee** [comment]
Well..I tested for a few more hours, the "gradio server freeze" problem mentioned by juan9999 actually still exists. The UI would sometimes stuck on:
![022-12-13 213949](https://user-images.githubusercontent.com/118984038/207340522-6cdad86d-e577-4c4d-afb9-ec2621604327.jpg)

The image will generate and show up. The generate button works afterwards. But the UI stucks like this forever (with generate button still functional) unless page refreshed.
This problem has been there since very early if I recall.

**Comment by Ktr4ks** [comment]
> update to the latest colab by clicking on the thumbnails on the main page of the repo

Already on the latest version. Also, the problem only seems to occur with txt2img, I'm having no problems with img2img.

**Comment by TheLastBen** [comment]
@gateeeeee maybe the button freezes but it's still functional, that's why I dragged it below the two white buttons in the first place.

**Comment by Ktr4ks** [comment]
This shouldn't be closed, the problem is still not solved, using the Gradio servers is just a workaround, and doesn't work as good as using a local tunnel.
